var age = 22;
var marks = 75;
var countries = ["Turkiye", "Dubai", "Pakistan", "Canada", "Italy"];
var percentage = 80;
var cities = ["Makkah", "Istanbol", "Toronto", "Lahore", "Paris"];
console.log((age >= 22) ? true : false);
console.log((age < 22) ? true : false);
console.log((marks >= 75) ? true : false);
console.log((marks < 75) ? true : false);
console.log((countries.includes("Pakistan")) ? true : false);
console.log((countries.includes("Malasiya")) ? true : false);
console.log((percentage >= 80) ? true : false);
console.log((percentage < 80) ? true : false);
console.log((cities.includes("Lahore")) ? true : false);
console.log((cities.includes("Gujrat")) ? true : false);
